FROM nginx
LABEL email=ashutoshh@linux.com 
ADD html-sample-app /usr/share/nginx/html/
# default location of nginx is /usr/share/nginx/html/
EXPOSE 80 
# just to let docker Engine know about the app port 
# optional field these days 