apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  creationTimestamp: null
  name: ashu-web
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ashu-web
  metrics:
  - type: Resource  # CPU utilization
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource  # Memory utilization
    resource:
      name: memory
      target:
        type: Utilization  # You can also use AverageValue for a specific memory target
        averageUtilization: 50  # A