apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashu-web
  name: ashu-web-lb
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ashu-web
  type: ClusterIP
status:
  loadBalancer: {}
